server {
    listen 8080;
    server_name _;

    location /api/ {
        proxy_pass http://api:8084;
        proxy_set_header X-Request-ID $http_x_request_id;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
